/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    articles: Article;
    journals: Journal;
    'policy-reviews': PolicyReview;
    'contact-submissions': ContactSubmission;
    subscribers: Subscriber;
    services: Service;
    'team-members': TeamMember;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    journals: JournalsSelect<false> | JournalsSelect<true>;
    'policy-reviews': PolicyReviewsSelect<false> | PolicyReviewsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {
    beranda: Beranda;
    'tentang-kami': TentangKami;
    kontak: Kontak;
    footer: Footer;
    navbar: Navbar;
  };
  globalsSelect: {
    beranda: BerandaSelect<false> | BerandaSelect<true>;
    'tentang-kami': TentangKamiSelect<false> | TentangKamiSelect<true>;
    kontak: KontakSelect<false> | KontakSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
  };
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Member dipertahankan untuk akun lama dan hanya memiliki akses baca. Gunakan Editor, Reviewer, Admin, atau Super Admin untuk akun baru.
   */
  role: 'super_admin' | 'admin' | 'editor' | 'reviewer' | 'member';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Deskripsikan gambar secara ringkas untuk aksesibilitas. Wajib untuk setiap media.
   */
  alt: string;
  caption?: string | null;
  /**
   * Cantumkan fotografer, organisasi, atau lisensi bila diperlukan.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola draft, proses review, dan publikasi artikel. Gunakan tombol Preview untuk memeriksa artikel yang sudah dipublikasikan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Digunakan pada card artikel, hasil pencarian, dan metadata SEO.
   */
  excerpt?: string | null;
  /**
   * Upload gambar baru atau pilih gambar dari Media Library. Gambar ini digunakan sebagai thumbnail dan hero artikel.
   */
  featuredImage?: (number | null) | Media;
  featuredImageCaption?: string | null;
  featuredImageCredit?: string | null;
  /**
   * Dipertahankan sementara untuk artikel lama. Gunakan “Gambar Utama Artikel” untuk konten baru.
   */
  imageUrl?: string | null;
  slug?: string | null;
  author?: (number | null) | User;
  category?: (number | null) | Category;
  /**
   * Editor dapat mengirim review; reviewer dapat menyetujui atau meminta revisi; hanya admin yang dapat menjadwalkan atau menerbitkan.
   */
  status?: ('draft' | 'in_review' | 'revision_requested' | 'approved' | 'scheduled' | 'published' | 'archived') | null;
  reviewNotes?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola metadata publikasi, dokumen PDF, proses review, dan status publikasi jurnal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journals".
 */
export interface Journal {
  id: number;
  title: string;
  abstract: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Opsional. Gunakan untuk ringkasan eksekutif atau konteks yang tampil pada halaman jurnal.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  document: number | Media;
  language: 'id' | 'en' | 'bilingual';
  publicationYear: number;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  doi?: string | null;
  issn?: string | null;
  authors: {
    name: string;
    affiliation?: string | null;
    email?: string | null;
    publicProfile?: string | null;
    id?: string | null;
  }[];
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Kosongkan untuk menggunakan URL jurnal pada website ini.
   */
  canonicalUrl?: string | null;
  ogImage?: (number | null) | Media;
  slug: string;
  author?: (number | null) | User;
  category?: (number | null) | Category;
  /**
   * Editor dapat mengirim review; reviewer dapat menyetujui atau meminta revisi; hanya admin yang dapat menjadwalkan atau menerbitkan.
   */
  status?: ('draft' | 'in_review' | 'revision_requested' | 'approved' | 'scheduled' | 'published' | 'archived') | null;
  reviewNotes?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-reviews".
 */
export interface PolicyReview {
  id: number;
  title: string;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dipakai pada metadata SEO dan preview Policy Review.
   */
  excerpt?: string | null;
  document: number | Media;
  slug?: string | null;
  author?: (number | null) | User;
  status: 'draft' | 'in_review' | 'revision_requested' | 'approved' | 'scheduled' | 'published' | 'archived';
  publishedAt?: string | null;
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  institution?: string | null;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  tagline: string;
  description: string;
  color: string;
  gradient: string;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  targetAudience?:
    | {
        audience: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  photo?: (number | null) | Media;
  name: string;
  initials: string;
  bio?: string | null;
  category: 'management' | 'expert';
  role?: string | null;
  expertise: string;
  institution?: string | null;
  color: string;
  /**
   * Semakin kecil angkanya, semakin atas tampilannya
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'journals';
        value: number | Journal;
      } | null)
    | ({
        relationTo: 'policy-reviews';
        value: number | PolicyReview;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  featuredImageCaption?: T;
  featuredImageCredit?: T;
  imageUrl?: T;
  slug?: T;
  author?: T;
  category?: T;
  status?: T;
  reviewNotes?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journals_select".
 */
export interface JournalsSelect<T extends boolean = true> {
  title?: T;
  abstract?: T;
  content?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  coverImage?: T;
  document?: T;
  language?: T;
  publicationYear?: T;
  volume?: T;
  issue?: T;
  pages?: T;
  doi?: T;
  issn?: T;
  authors?:
    | T
    | {
        name?: T;
        affiliation?: T;
        email?: T;
        publicProfile?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  ogImage?: T;
  slug?: T;
  author?: T;
  category?: T;
  status?: T;
  reviewNotes?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-reviews_select".
 */
export interface PolicyReviewsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  excerpt?: T;
  document?: T;
  slug?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  institution?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  color?: T;
  gradient?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  targetAudience?:
    | T
    | {
        audience?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  photo?: T;
  name?: T;
  initials?: T;
  bio?: T;
  category?: T;
  role?: T;
  expertise?: T;
  institution?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beranda".
 */
export interface Beranda {
  id: number;
  visibility?: {
    showHero?: boolean | null;
    showStats?: boolean | null;
    showPartners?: boolean | null;
    showServices?: boolean | null;
    showArticles?: boolean | null;
    showTeam?: boolean | null;
    showCTA?: boolean | null;
  };
  hero: {
    badge: string;
    title: string;
    titleHighlight: string;
    titleSuffix: string;
    description: string;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  stats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        icon?: ('Mic2' | 'Users' | 'Building2' | 'Globe' | 'Target' | 'CheckCircle2') | null;
        id?: string | null;
      }[]
    | null;
  partners: {
    title: string;
    list?:
      | {
          name: string;
          /**
           * Logo perusahaan/instansi. Sebaiknya menggunakan latar transparan (PNG).
           */
          logo?: (number | null) | Media;
          /**
           * Isi dengan URL gambar jika tidak mengunggah logo di atas.
           */
          logoUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  servicesIntro: {
    badge: string;
    /**
     * Gunakan HTML <br /> untuk membuat baris baru. Contoh: Solusi Lengkap untuk<br />Penguatan Kapasitas Instansi
     */
    title: string;
    description: string;
  };
  featuredData?: {
    /**
     * Pilih layanan yang ingin ditampilkan di halaman Beranda (maksimal 6 disarankan).
     */
    services?: (number | Service)[] | null;
    /**
     * Pilih artikel yang ingin ditampilkan di halaman Beranda (maksimal 3 disarankan).
     */
    articles?: (number | Article)[] | null;
    /**
     * Pilih anggota tim yang ingin ditampilkan di halaman Beranda (maksimal 4 disarankan).
     */
    team?: (number | TeamMember)[] | null;
  };
  cta: {
    /**
     * Gunakan Enter/Baris Baru untuk memisahkan baris teks.
     */
    title: string;
    description: string;
    /**
     * Gunakan format internasional tanpa awalan + (contoh: 62812...)
     */
    waNumber: string;
    waMessage: string;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tentang-kami".
 */
export interface TentangKami {
  id: number;
  hero: {
    /**
     * Unggah gambar untuk mengganti background warna gradient di hero section.
     */
    backgroundImage?: (number | null) | Media;
    badge: string;
    title: string;
    titleHighlight: string;
    description: string;
  };
  stats?:
    | {
        value: string;
        label: string;
        icon: 'CheckCircle2' | 'Award' | 'Target' | 'Eye' | 'Users' | 'Building2' | 'Globe' | 'BookOpen';
        id?: string | null;
      }[]
    | null;
  profil: {
    paragraph1: string;
    paragraph2: string;
    paragraph3: string;
  };
  visi: string;
  misi?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  coreValues?:
    | {
        letter: string;
        name: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  ceoMessage: {
    /**
     * Pilih anggota tim yang akan ditampilkan sebagai CEO di halaman ini.
     */
    ceo: number | TeamMember;
    quote: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontak".
 */
export interface Kontak {
  id: number;
  heroTitle: string;
  heroSubtitle: string;
  phone: string;
  email: string;
  address: string;
  workingHours: string;
  /**
   * Teks singkat untuk ikon pin peta (misal: Jakarta Selatan, DKI Jakarta)
   */
  locationTag: string;
  whatsappCta: {
    title: string;
    subtitle: string;
    defaultMessage: string;
  };
  /**
   * Daftar pilihan keperluan / subjek yang akan muncul di dropdown formulir kontak.
   */
  formSubjects?:
    | {
        subject: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  companyDescription: string;
  socialMedia?:
    | {
        platform: 'instagram' | 'youtube' | 'linkedin' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  linksCompany?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  linksServices?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tahun akan ditambahkan secara otomatis (contoh: © 2026 PT Mahaga Widya Cita. Hak Cipta Dilindungi.)
   */
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  links: {
    label: string;
    href: string;
    children?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beranda_select".
 */
export interface BerandaSelect<T extends boolean = true> {
  visibility?:
    | T
    | {
        showHero?: T;
        showStats?: T;
        showPartners?: T;
        showServices?: T;
        showArticles?: T;
        showTeam?: T;
        showCTA?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        title?: T;
        list?:
          | T
          | {
              name?: T;
              logo?: T;
              logoUrl?: T;
              id?: T;
            };
      };
  servicesIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  featuredData?:
    | T
    | {
        services?: T;
        articles?: T;
        team?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        waNumber?: T;
        waMessage?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tentang-kami_select".
 */
export interface TentangKamiSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        badge?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  profil?:
    | T
    | {
        paragraph1?: T;
        paragraph2?: T;
        paragraph3?: T;
      };
  visi?: T;
  misi?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  coreValues?:
    | T
    | {
        letter?: T;
        name?: T;
        desc?: T;
        id?: T;
      };
  ceoMessage?:
    | T
    | {
        ceo?: T;
        quote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontak_select".
 */
export interface KontakSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  phone?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  locationTag?: T;
  whatsappCta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        defaultMessage?: T;
      };
  formSubjects?:
    | T
    | {
        subject?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyDescription?: T;
  socialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  linksCompany?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  linksServices?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}